# Generated by Django 3.2.3 on 2021-06-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(verbose_name='Дата отпарвления')),
                ('arrival_date', models.DateField(verbose_name='Дата доставки')),
                ('cost', models.IntegerField(verbose_name='Стоимость доставки, ₽')),
                ('salary_part', models.IntegerField(verbose_name='Часть зарплаты курьера, ₽')),
                ('status', models.CharField(choices=[('0', 'Поиск курьера'), ('1', 'Курьер движется к отправителю'), ('2', 'Курьер движется к получателю'), ('3', 'Подтверждение личности получателя'), ('4', 'Передача посылки получателю'), ('5', 'Завершено')], max_length=10, verbose_name='Статус заказа')),
                ('address_from', models.CharField(max_length=100, verbose_name='Адрес отправления')),
                ('address_to', models.CharField(max_length=100, verbose_name='Адрес получения')),
                ('sender', models.CharField(max_length=100, verbose_name='ФИО отправителя')),
                ('recipient', models.CharField(max_length=100, verbose_name='ФИО получателя')),
                ('pointFromLat', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Широта точки отправителя')),
                ('pointFromLng', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Долгота точки отправителя')),
                ('pointToLat', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Широта точки получателя')),
                ('pointToLng', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Долгота точки получателя')),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.courier', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
