# Generated by Django 3.2.4 on 2021-06-06 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210606_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.courier', verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Поиск курьера'), ('1', 'Курьер движется к отправителю'), ('2', 'Курьер движется к получателю'), ('3', 'Подтверждение личности получателя'), ('4', 'Передача посылки получателю'), ('5', 'Завершено')], default='0', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
