# Generated by Django 3.2.4 on 2021-06-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210606_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parcel_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ценность посылки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('card', 'Картой онлайн'), ('cash', 'Наличными курьеру')], default='cash', max_length=4, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.CharField(choices=[('1', 'До 1 кг'), ('5', 'До 5 кг'), ('10', 'До 10 кг'), ('15', 'До 15 кг')], default='1', max_length=2, verbose_name='Вес заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pointFromLat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Широта точки отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pointFromLng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Долгота точки отправителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pointToLat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Широта точки получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pointToLng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Долгота точки получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Поиск курьера'), ('1', 'Курьер движется к отправителю'), ('2', 'Курьер движется к получателю'), ('3', 'Подтверждение личности получателя'), ('4', 'Передача посылки получателю'), ('5', 'Завершено')], default='0', max_length=1, verbose_name='Статус заказа'),
        ),
    ]
