# Generated by Django 3.2.4 on 2021-06-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210606_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_way',
            field=models.CharField(choices=[('onfoot', 'Пешком'), ('oncar', 'На машине')], default='oncar', max_length=6, verbose_name='Как доставить'),
        ),
    ]
